CREATE DATABASE IF NOT EXISTS books CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'app'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON books.* TO 'app'@'%';
FLUSH PRIVILEGES;
